apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: integrationHub-dev-clusster
  region: ap-southeast-1
  version: "1.21"
managedNodeGroups:
- name: primary
  instanceType: t2.small
  minSize: 3
  maxSize: 6
  spot: true